version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # Maintain dependencies for SvelteKit
  - package-ecosystem: "npm"
    directory: "/services/frontend"
    schedule:
      interval: "daily"
    # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/services/backend"
    schedule:
      interval: "daily"
