version: "3"

networks:
  intranet:
    internal: false
    driver: bridge

services:
  reverse-proxy:
    image: "traefik:latest"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    networks:
      - intranet

  frontend:
    image: node:latest
    container_name: web-ui
    volumes:
      - ./sveltekit/tailwind.config.cjs:/app/tailwind.config.cjs
      - ./sveltekit/postcss.config.cjs:/app/postcss.config.cjs
      - ./sveltekit/package.json:/app/package.json
      - ./sveltekit/svelte.config.js:/app/svelte.config.js
      - ./sveltekit/tsconfig.json:/app/tsconfig.json
      - ./sveltekit/vite.config.ts:/app/vite.config.ts
      - ./sveltekit/static:/app/static
      - ./sveltekit/src:/app/src
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`web.localhost`)&&PathPrefix(`/`)"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
      - "traefik.http.routers.frontend.entrypoints=web"
    command: ["sh", "-c", "cd /app && npm install && npm run dev"]

  backend:
    image: golang:latest
    container_name: web-api
    volumes:
      - ./golang:/app
    networks:
      - intranet
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`web.localhost`)&&(PathPrefix(`/api`)||PathPrefix(`/swagger`))"
      - "traefik.http.routers.backend.priority=2"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.backend.entrypoints=web"
    command: ["sh", "-c", "cd /app && bash devops/scripts/run-local-docker.sh"]

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - intranet
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s
      timeout: 5s
      retries: 5
