database:
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  database: postgres
  sslmode: 0

webserver:
  host: 127.0.0.1
  port: 3000
  show_frontend: 1
  show_swagger: 1

security:
  jwtsecret: loafofbread
  secretgreet: "Secret Hello World"