apiVersion: v2
name: ingress
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: traefik
    version: 21.1.0
    repository: https://traefik.github.io/charts
