name: "CI: Test Software"

on:
  push:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    continue-on-error: true

    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          PGDATA: /var/lib/postgresql/data/pgdata
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Wait for Postgres to become available (max 20 seconds)
        run: |
          timeout 20 bash -c 'until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to become available..."
            sleep 2
          done'
          if ! pg_isready -h localhost -p 5432 -U postgres; then
            echo "PostgreSQL is not available after 20 seconds."
            exit 1
          fi
          echo "PostgreSQL is available now."

      - name: run backend tests
        if: ${{ always() }}
        run: make test-be-ci
        env:
          APP_DATABASE_HOST: 127.0.0.1
          APP_DATABASE_PORT: 5432
          APP_DATABASE_USERNAME: postgres
          APP_DATABASE_PASSWORD: postgres
          APP_DATABASE_DATABASE: postgres
          APP_DATABASE_SSLMODE: False

  test-frontend:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: run frontend tests
        if: ${{ always() }}
        run: make test-fe-ci

  test-result:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    if: ${{ always() }}

    steps:
      - name: Check if any tests failed
        run: |
          if [ "${{ needs.test-backend.result }}" == "failure" ] || [ "${{ needs.test-frontend.result }}" == "failure" ]; then
            echo "One or more tests failed."
            exit 1
          else
            echo "All tests passed."
          fi
