name: "CI: Test Software"

on:
  push:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: run backend tests
        if: ${{ always() }}
        run: make test-be
        env:
          APP_DATABASE_HOST: postgres
          APP_DATABASE_PORT: 5432
          APP_DATABASE_USERNAME: postgres
          APP_DATABASE_PASSWORD: postgres
          APP_DATABASE_DATABASE: postgres
          APP_DATABASE_SSLMODE: False

  test-frontend:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: run frontend tests
        if: ${{ always() }}
        run: make test-fe

  test-result:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    if: ${{ always() }}

    steps:
      - name: Check if any tests failed
        run: |
          if [ "${{ needs.test-backend.result }}" == "failure" ] || [ "${{ needs.test-frontend.result }}" == "failure" ]; then
            echo "One or more tests failed."
            exit 1
          else
            echo "All tests passed."
          fi
