name: "CI: Test Software"

on:
  push:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    # continue-on-error: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: run backend tests
        if: ${{ always() }}
        run: make test-be
        env:
          APP_DATABASE_HOST: postgres
          APP_DATABASE_PORT: 5432
          APP_DATABASE_USERNAME: postgres
          APP_DATABASE_PASSWORD: postgres
          APP_DATABASE_DATABASE: postgres
          APP_DATABASE_SSLMODE: False

  # test-frontend:
  #   runs-on: ubuntu-latest
  #   continue-on-error: true

  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: run frontend tests
  #       if: ${{ always() }}
  #       run: make test-fe
