name: iac-destroy

on:
  workflow_dispatch:
    inputs:
      cloud_provider:
        description: "Wähle einen Cloud Provider aus:"
        type: choice
        required: true
        default: "civo"
        options:
          - civo
          - hetzner
          - azure

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install terraform
        uses: hashicorp/setup-terraform@v3

      - name: deploy terraform
        run: (cd ./devops/deployments ; make destroy-infrastructure-${{ inputs.cloud_provider }})
        env:
          TF_VAR_civo_token: ${{ secrets.civo_token }}

      - name: delete kubeconfig secret
        run: gh secret delete KUBECONFIG_${{ inputs.cloud_provider }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
